# Schedule I 한글패치 통합 설치기
# 모드 로더(BepInEx 또는 MelonLoader)와 번역기가 없으면 공식 저장소에서 자동 설치합니다.
param([string]$Loader = "")
$ErrorActionPreference = "Stop"
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
try { Get-ChildItem $here -Recurse -File | Unblock-File -ErrorAction SilentlyContinue } catch {}
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
. (Join-Path $here "common.ps1")

$XuatVersion = "5.6.1"
$MelonVersion = "0.7.3"

Write-Host "==============================================" -ForegroundColor Cyan
Write-Host "   Schedule I 한글패치 설치기" -ForegroundColor Cyan
Write-Host "==============================================" -ForegroundColor Cyan

# ---------- 1) 게임 경로 ----------
$gamePath = Resolve-GamePath
if (-not $gamePath) { pause; exit 1 }
Write-Host ("게임 경로: " + $gamePath) -ForegroundColor Green

if (Get-Process -Name "Schedule I" -ErrorAction SilentlyContinue) {
    Write-Host "게임이 실행 중입니다. 완전히 종료한 뒤 다시 실행해주세요." -ForegroundColor Red
    pause; exit 1
}

$tmp = Join-Path $env:TEMP "s1kr_setup"
New-Item -ItemType Directory -Force $tmp | Out-Null

function Get-Zip([string]$url, [string]$name) {
    $zip = Join-Path $tmp ($name + ".zip")
    $dir = Join-Path $tmp $name
    Invoke-WebRequest -Uri $url -OutFile $zip -UseBasicParsing
    if (Test-Path $dir) { Remove-Item $dir -Recurse -Force }
    Expand-Archive $zip $dir -Force
    return $dir
}

function Test-XuatVersion([string]$dll) {
    if (-not (Test-Path $dll)) { return $false }
    $v = [System.Diagnostics.FileVersionInfo]::GetVersionInfo($dll).FileVersion
    return ($v -and ([version]$v -ge [version]$XuatVersion))
}

function Install-Config([string]$cfg) {
    New-Item -ItemType Directory -Force (Split-Path $cfg) | Out-Null
    $me = "$env:USERDOMAIN\$env:USERNAME"
    if (Test-Path $cfg) { & icacls "$cfg" /remove:d "$me" 2>&1 | Out-Null }
    Copy-Item (Join-Path $here "payload\config\AutoTranslatorConfig.ini") $cfg -Force
    & icacls "$cfg" /deny "${me}:(WD,AD,WEA,WA)" 2>&1 | Out-Null
}

function Install-Texts([string]$langDir) {
    $textDir = Join-Path $langDir "Text"
    New-Item -ItemType Directory -Force $textDir | Out-Null
    foreach ($f in (Get-ChildItem (Join-Path $here "payload\Text") -Filter "*.txt")) {
        Copy-Item $f.FullName (Join-Path $textDir $f.Name) -Force
    }
    $stale = Join-Path $textDir "_AutoGeneratedTranslations.txt"
    if (Test-Path $stale) { Remove-Item $stale -Force }
    $out = Join-Path $langDir "_AutoGeneratedOutput.txt"
    if (-not (Test-Path $out)) { New-Item -ItemType File $out | Out-Null }
}

# ---------- 2) 설치 방식 결정 ----------
$state = Get-LoaderState $gamePath
$mode = $null
if ($Loader -match '^(?i)melon') { $mode = "Melon" }
elseif ($Loader -match '^(?i)bep') { $mode = "BepInEx" }
elseif ($state.Melon) {
    $mode = "Melon"
    Write-Host ""
    Write-Host "MelonLoader(넥서스 모드용 로더)가 설치되어 있습니다." -ForegroundColor Yellow
    Write-Host "다른 모드와 함께 쓸 수 있도록 MelonLoader 방식으로 설치합니다." -ForegroundColor Yellow
}
elseif ($state.BepFiles) { $mode = "BepInEx" }
else {
    Write-Host ""
    Write-Host "----------------------------------------------" -ForegroundColor Yellow
    Write-Host " 넥서스 모드(Nexus Mods)도 함께 쓰실 건가요?" -ForegroundColor Yellow
    Write-Host ""
    Write-Host " 넥서스의 Schedule I 모드는 대부분 MelonLoader가 필요합니다."
    Write-Host " 다른 모드를 쓸 계획이 있으면 M, 한글패치만 쓸 거라면 그냥 엔터."
    Write-Host "----------------------------------------------" -ForegroundColor Yellow
    $ans = Read-Host " [Enter] 한글패치만 (기본) / [M] 넥서스 모드도 사용"
    if ($ans -match '^[Mmㅡ]') { $mode = "Melon" } else { $mode = "BepInEx" }
}
Write-Host ("설치 방식: " + $(if ($mode -eq "Melon") { "MelonLoader" } else { "BepInEx" })) -ForegroundColor Green

if ($mode -eq "BepInEx") {
    # ---------- 3-B) BepInEx ----------
    $off = Join-Path $gamePath "winhttp.dll.disabled_by_korean_patch"
    if ($state.BepActive) {
        Write-Host "[1/4] BepInEx 이미 설치됨 - 건너뜀" -ForegroundColor DarkGray
    } elseif ($state.BepFiles -and (Test-Path $off)) {
        Rename-Item $off "winhttp.dll"
        Write-Host "[1/4] 꺼져 있던 BepInEx를 다시 켰습니다" -ForegroundColor Green
    } else {
        Write-Host "[1/4] BepInEx 다운로드 중... (공식 빌드 서버)" -ForegroundColor Cyan
        $dir = Get-Zip "https://builds.bepinex.dev/projects/bepinex_be/733/BepInEx-Unity.IL2CPP-win-x64-6.0.0-be.733%2B995f049.zip" "bepinex"
        Copy-Item (Join-Path $dir "*") $gamePath -Recurse -Force
        Write-Host "  BepInEx 설치 완료" -ForegroundColor Green
    }

    if (-not (Test-XuatVersion (Join-Path $gamePath "BepInEx\plugins\XUnity.AutoTranslator\XUnity.AutoTranslator.Plugin.Core.dll"))) {
        Write-Host "[2/4] XUnity.AutoTranslator $XuatVersion 다운로드 중... (GitHub 공식)" -ForegroundColor Cyan
        $dir = Get-Zip "https://github.com/bbepis/XUnity.AutoTranslator/releases/download/v$XuatVersion/XUnity.AutoTranslator-BepInEx-IL2CPP-$XuatVersion.zip" "xuat_bep"
        Copy-Item (Join-Path $dir "BepInEx\*") (Join-Path $gamePath "BepInEx\") -Recurse -Force
        Write-Host "  번역기 설치 완료" -ForegroundColor Green
    } else {
        Write-Host "[2/4] 번역기 $XuatVersion+ 이미 설치됨 - 건너뜀" -ForegroundColor DarkGray
    }

    Write-Host "[3/4] 한글 번역 파일 설치 중..." -ForegroundColor Cyan
    Install-Texts (Join-Path $gamePath "BepInEx\Translation\ko")
    Copy-Item (Join-Path $here "payload\KoreanTextFixer.dll") (Join-Path $gamePath "BepInEx\plugins\KoreanTextFixer.dll") -Force
    Write-Host "  번역 58,000여 개 + 보조 플러그인 설치 완료" -ForegroundColor Green

    Write-Host "[4/4] 번역기 설정 적용 중..." -ForegroundColor Cyan
    Install-Config (Join-Path $gamePath "BepInEx\config\AutoTranslatorConfig.ini")
    Write-Host "  설정 적용 및 잠금 완료 (게임이 설정을 되돌리는 것 방지)" -ForegroundColor Green
}
else {
    # ---------- 3-M) MelonLoader ----------
    if (-not $state.Melon) {
        Write-Host "[1/4] MelonLoader $MelonVersion 다운로드 중... (GitHub 공식)" -ForegroundColor Cyan
        $dir = Get-Zip "https://github.com/LavaGang/MelonLoader/releases/download/v$MelonVersion/MelonLoader.x64.zip" "melonloader"
        Copy-Item (Join-Path $dir "*") $gamePath -Recurse -Force
        Write-Host "  MelonLoader 설치 완료" -ForegroundColor Green
    } else {
        Write-Host "[1/4] MelonLoader 이미 설치됨 - 건너뜀" -ForegroundColor DarkGray
    }

    # BepInEx와 MelonLoader가 동시에 켜져 있으면 서로 충돌하므로 BepInEx를 끈다 (파일은 그대로 둠)
    if ($state.BepActive) {
        $ours = @("XUnity.AutoTranslator", "XUnity.ResourceRedirector", "KoreanTextFixer.dll")
        $others = @(Get-ChildItem (Join-Path $gamePath "BepInEx\plugins") -ErrorAction SilentlyContinue | Where-Object { $ours -notcontains $_.Name -and ($_.PSIsContainer -or $_.Extension -eq ".dll") })
        if ($others.Count -gt 0) {
            Write-Host ""
            Write-Host "BepInEx에 한글패치 외의 플러그인이 있습니다:" -ForegroundColor Yellow
            $others | ForEach-Object { Write-Host ("  - " + $_.Name) }
            Write-Host "BepInEx와 MelonLoader는 동시에 쓸 수 없어서, 계속하면 위 플러그인은 작동하지 않게 됩니다." -ForegroundColor Yellow
            $ans = Read-Host " 계속할까요? [Y] 예 / [N] 아니오"
            if (-not ($ans -eq "" -or $ans -match '^[YyㅛJj]')) { Write-Host "설치를 취소했습니다." ; pause; exit 1 }
        }
        Rename-Item (Join-Path $gamePath "winhttp.dll") "winhttp.dll.disabled_by_korean_patch" -Force
        Write-Host "  MelonLoader와 충돌하는 BepInEx를 껐습니다 (MelonLoader를 지우고 설치.bat을 다시 실행하면 BepInEx로 돌아갑니다)" -ForegroundColor Green
    }

    if (-not (Test-XuatVersion (Join-Path $gamePath "UserLibs\XUnity.AutoTranslator.Plugin.Core.dll"))) {
        Write-Host "[2/4] XUnity.AutoTranslator $XuatVersion (MelonLoader판) 다운로드 중... (GitHub 공식)" -ForegroundColor Cyan
        $dir = Get-Zip "https://github.com/bbepis/XUnity.AutoTranslator/releases/download/v$XuatVersion/XUnity.AutoTranslator-MelonMod-IL2CPP-$XuatVersion.zip" "xuat_melon"
        New-Item -ItemType Directory -Force (Join-Path $gamePath "Mods") | Out-Null
        Copy-Item (Join-Path $dir "Mods\XUnity.AutoTranslator.Plugin.MelonMod.dll") (Join-Path $gamePath "Mods\") -Force
        Copy-Item (Join-Path $dir "UserLibs") $gamePath -Recurse -Force
        Write-Host "  번역기 설치 완료" -ForegroundColor Green
    } else {
        Write-Host "[2/4] 번역기 $XuatVersion+ 이미 설치됨 - 건너뜀" -ForegroundColor DarkGray
    }

    Write-Host "[3/4] 한글 번역 파일 설치 중..." -ForegroundColor Cyan
    Install-Texts (Join-Path $gamePath "AutoTranslator\Translation\ko")
    New-Item -ItemType Directory -Force (Join-Path $gamePath "Mods") | Out-Null
    Copy-Item (Join-Path $here "payload\melon\KoreanTextFixer.dll") (Join-Path $gamePath "Mods\KoreanTextFixer.dll") -Force
    Write-Host "  번역 58,000여 개 + 보조 모드 설치 완료" -ForegroundColor Green

    Write-Host "[4/4] 번역기 설정 적용 중..." -ForegroundColor Cyan
    Install-Config (Join-Path $gamePath "AutoTranslator\Config.ini")
    Write-Host "  설정 적용 및 잠금 완료 (게임이 설정을 되돌리는 것 방지)" -ForegroundColor Green
}

# ---------- 4) 폰트 적용 여부 확인 ----------
Write-Host ""
Write-Host "----------------------------------------------" -ForegroundColor Yellow
Write-Host " 한글 폰트(을지로체)도 적용할까요?" -ForegroundColor Yellow
Write-Host ""
Write-Host " 게임 기본 폰트에는 한글이 없어서, 적용하지 않으면"
Write-Host " 번역된 글자가 네모(ㅁ)로 깨져 보일 수 있습니다."
Write-Host ""
Write-Host " * 게임 원본 파일 1개를 수정합니다 (원본은 자동 백업)"
Write-Host " * 되돌리려면: Steam > 속성 > 설치된 파일 > 파일 무결성 확인"
Write-Host "----------------------------------------------" -ForegroundColor Yellow
$ans = Read-Host " 적용하시겠습니까? [Y] 예 (권장) / [N] 아니오"
if ($ans -eq "" -or $ans -match '^[YyㅛJj]') {
    Write-Host ""
    Write-Host "[폰트] 을지로체 적용 중..." -ForegroundColor Cyan
    $fontScript = Join-Path $here "font_patch.ps1"
    if (Test-Path $fontScript) {
        & powershell -NoProfile -ExecutionPolicy Bypass -File $fontScript -NoPause -GamePath "$gamePath"
        if ($LASTEXITCODE -eq 0) { Write-Host "  폰트 적용 완료" -ForegroundColor Green }
        else { Write-Host "  폰트 적용에 실패했습니다. 나중에 '폰트적용.bat'을 실행해보세요." -ForegroundColor Yellow }
    } else {
        Write-Host "  font_patch.ps1 을 찾을 수 없습니다." -ForegroundColor Yellow
    }
} else {
    Write-Host " 폰트는 건너뜁니다. 나중에 '폰트적용.bat'으로 적용할 수 있습니다." -ForegroundColor DarkGray
}

Write-Host ""
Write-Host "==============================================" -ForegroundColor Green
Write-Host "   설치 완료! 게임을 실행하세요." -ForegroundColor Green
Write-Host "==============================================" -ForegroundColor Green
if ($mode -eq "Melon") {
    Write-Host ""
    Write-Host " MelonLoader를 처음 설치했다면 첫 실행에 1~3분 정도 더 걸립니다." -ForegroundColor Yellow
    Write-Host " (게임 코드를 변환하는 과정이며 인터넷이 필요합니다. 두 번째부터는 빠릅니다)" -ForegroundColor Yellow
    Write-Host " 넥서스 모드는 게임 폴더의 Mods 폴더에 넣으면 한글패치와 함께 작동합니다." -ForegroundColor Yellow
}
pause
